site_name: Apuntes Montaje-Sistemas Informaticos I.E.S. Rafael Alberti (CÃ¡diz)
site_url: https://axisalberti.github.io/Axis_Apuntes
repo_url: https://github.com/AxisAlberti/Axis_Apuntes
repo_name: GitHub
edit_uri: edit/main/docs/
site_author: Jose Manuel Gonzalez Castillo
exclude_docs: "**/*.gift"
nav:
- Principal: index.md
- Montaje y Mantenimiento:
  - section1/index.md
  - Unidad 00 - Sistemas de numeracion:
    - section1/u00/index.md
    - MM U00.1. Sistemas de numeracion: section1/u00/teoria/MM-U00.1.-Sistemas-de-numeracion.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 01 - Introduccion a los sistemas informaticos:
    - section1/u01/index.md
    - MM U01.1. Introduccion a los sistemas informaticos: section1/u01/teoria/MM-U01.1.-Introduccion-a-los-sistemas-informaticos.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 02 - Componentes internos del PC:
    - section1/u02/index.md
    - MM U02.1. Componentes internos del PC: section1/u02/teoria/MM-U02.1.-Componentes-internos-del-PC.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 03 - Chipset:
    - section1/u03/index.md
    - MM U03.1. Chipset: section1/u03/teoria/MM-U03.1.-Chipset.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 04 - Conexiones externas:
    - section1/u04/index.md
    - MM U04.1. Conexiones externas: section1/u04/teoria/MM-U04.1.-Conexiones-externas.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 05 - Memoria RAM:
    - section1/u05/index.md
    - MM U05.1. Memoria RAM: section1/u05/teoria/MM-U05.1.-Memoria-RAM.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 06 - CMOS y UEFI:
    - section1/u06/index.md
    - MM U06.1. CMOS y UEFI: section1/u06/teoria/MM-U06.1.-CMOS-y-UEFI.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 07 - Almacenamiento:
    - section1/u07/index.md
    - MM U07.1. Almacenamiento: section1/u07/teoria/MM-U07.1.-Almacenamiento.md
    - Presentacion: section1/slides/no-disponible.md
  - Unidad 08 - Microprocesadores:
    - section1/u08/index.md
    - MM U08.1. Microprocesadores: section1/u08/teoria/MM-U08.1.-Microprocesadores.md
    - Presentacion: section1/slides/no-disponible.md
  - Anexo 1 - Arquitecturas de procesadores:
    - section1/A1/index.md
    - A1.1 Arquitecturas de procesadores: section1/A1/teoria/A1-1-Arquitecturas-de-procesadores.md
    - Presentacion: section1/slides/no-disponible.md
  - Anexo 2 - Procesos e hilos:
    - section1/A2/index.md
    - A2.1 Procesos e hilos: section1/A2/teoria/A2-1-Procesos-e-hilos.md
    - Presentacion: section1/slides/no-disponible.md
  - Anexo 3 - Prevencion de riesgos laborales:
    - section1/A3/index.md
    - A3.1 Prevencion de riesgos laborales: section1/A3/teoria/A3-1-Prevencion-de-riesgos-laborales.md
    - Presentacion: section1/A3/slides/PRL-slide-prueba.html
  - Anexo 4 - Guia para elegir procesador:
    - section1/A4/index.md
    - A4.1 Guia para elegir procesador: section1/A4/teoria/A4-1-Guia-para-elegir-procesador.md
    - Presentacion: section1/slides/no-disponible.md
  - Anexo 5 - Nomenclatura de procesadores:
    - section1/A5/index.md
    - A5.1 Nomenclatura de procesadores: section1/A5/teoria/A5-1-Nomenclatura-de-procesadores.md
    - Presentacion: section1/slides/no-disponible.md
- Sistemas Informaticos:
  - section2/index.md
  - Unidad 01 - Redes:
    - section2/u01/index.md
    - SI U01.1. Redes: section2/u01/teoria/SI-U01.1.-Redes.md
    - Presentacion: section2/slides/no-disponible.md
  - Unidad 02 - Terminal:
    - section2/u02/index.md
    - SI U02.1. Terminal: section2/u02/teoria/SI-U02.1.-Terminal.md
    - Presentacion: section2/slides/no-disponible.md
- Blog: blog.md
- Tags: tags.md
- Acerca de: about.md
theme:
  name: material
  language: es
  logo: assets/axis.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: white
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.tracking
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - content.tooltips
  - search.suggest
  - search.highlight
  - search.share
  - content.code.annotate
  icon:
    tag:
      etiqueta: octicons/tag-24
extra_css:
- stylesheets/extra.css
markdown_extensions:
- toc:
    permalink: true
    title: Contenidos
- tables
- meta
- abbr
- attr_list
- md_in_html
- admonition
- def_list
- footnotes
- meta
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.snippets:
    auto_append:
    - includes/abbreviations.md
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tilde
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.blocks.caption
plugins:
- tags:
    tags_file: tags.md
- search:
    lang: es
- blogging:
    locale: es
    dirs:
    - blog
    size: 5
    paging: true
    show_total: true
    theme:
      name: card
    features:
      tags: {}
extra:
  version:
    provider: mike
  tags:
    etiqueta: etiqueta
  search:
    language: es
  analytics:
    provider: google
    property: G-GT5TGHD4YQ
    feedback:
      title: "\xBFTe ha sido \xFAtil la p\xE1gina?"
      ratings:
      - icon: material/emoticon-happy-outline
        name: Me ha sido de utilidad.
        data: 1
        note: Gracias por tu feedback!
      - icon: material/emoticon-sad-outline
        name: "La p\xE1gina podr\xEDa mejorar."
        data: 0
        note: "Gracias por tu feedback! Ay\xFAdame a mejorarla usando este formulario.\
          \ <a href=\"https://forms.gle/bBtzHfjb41unBb5o9\" target=_blank>feedback\
          \ form</a>."
  generator: false
copyright: "2026 Jose Manuel Gonzalez Castillo - Licencia CC BY-NC-SA"
