site_name: Apuntes FP - Informatica
theme:
  name: material
  language: es
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - navigation.top
nav:
- Principal: index.md
- Montaje y Mantenimiento:
  - section1/index.md
  - Unidad 00:
    - section1/u00/index.md
    - Teoria U00: section1/u00/teoria/MM-U00.1.-Sistemas-de-numeracion.md
  - Unidad 01:
    - section1/u01/index.md
    - Teoria U01: section1/u01/teoria/MM-U01.1.-Introduccion-a-los-sistemas-informaticos.md
  - Unidad 02:
    - section1/u02/index.md
    - Teoria U02: section1/u02/teoria/MM-U02.1.-Componentes-internos-del-PC.md
  - Unidad 03:
    - section1/u03/index.md
    - Teoria U03: section1/u03/teoria/MM-U03.1.-Chipset.md
  - Unidad 04:
    - section1/u04/index.md
    - Teoria U04: section1/u04/teoria/MM-U04.1.-Conexiones-externas.md
  - Unidad 05:
    - section1/u05/index.md
    - Teoria U05: section1/u05/teoria/MM-U05.1.-Memoria-RAM.md
  - Unidad 06:
    - section1/u06/index.md
    - Teoria U06: section1/u06/teoria/MM-U06.1.-CMOS-y-UEFI.md
  - Unidad 07:
    - section1/u07/index.md
    - Teoria U07: section1/u07/teoria/MM-U07.1.-Almacenamiento.md
  - Unidad 08:
    - section1/u08/index.md
    - Teoria U08: section1/u08/teoria/MM-U08.1.-Microprocesadores.md
  - Unidad 09:
    - section1/u09/index.md
    - Teoria U09: section1/u09/teoria/MM-U09.1.-Arquitecturas-de-procesadores.md
  - Unidad 10:
    - section1/u10/index.md
    - Teoria U10: section1/u10/teoria/MM-U10.1.-Procesos-e-hilos.md
  - Unidad 11:
    - section1/u11/index.md
    - Teoria U11: section1/u11/teoria/MM-U11.1.-Prevencion-de-riesgos-laborales.md
  - Unidad 12:
    - section1/u12/index.md
    - Teoria U12: section1/u12/teoria/MM-U12.1.-Guia-para-elegir-procesador.md
  - Unidad 13:
    - section1/u13/index.md
    - Teoria U13: section1/u13/teoria/MM-U13.1.-Nomenclatura-de-procesadores.md
- Sistemas Informaticos:
  - section2/index.md
  - Unidad 01:
    - section2/u01/index.md
    - Teoria U01: section2/u01/teoria/SI-U01.1.-Redes.md
  - Unidad 02:
    - section2/u02/index.md
    - Teoria U02: section2/u02/teoria/SI-U02.1.-Terminal.md
